
version: 2

models:
  - name: stg_customers
    description: "Staging table for the customers dataset with cleaned and standardized fields"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "The natural id pertaining to the customer"
        data_tests:
          - unique
          - not_null
      - name: zip_code_prefix
        description: "The zip code of the customer referencing the geolocation"
        data_tests:
          - not_null
      - name: city
        description: "The city which the customer belongs to or lives"
        data_tests:
          - not_null
      - name: state
        description: "The state where the city of the customer is"
        data_tests:
          - not_null
  - name: stg_geolocation
    columns:
      - name: zip_code_prefix
        description: "The primary key for this table being referenced by the customers and sellers table"
        data_tests:
          - not_null
      - name: latitude
        description: "An estimated reference point in latitude"
        data_tests:
          - not_null
      - name: longitude
        descripion: "An estimated reference point in longitude"
        data_tests:
          - not_null
      - name: city
        description: "The city where the zip code is based from"
        data_tests:
          - not_null
      - name: state
        description: "The state where the zip code is based from"
        data_tests:
          - not_null
  - name: stg_order_items
    columns:
      - name: order_id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: order_item_num
        description: "The number of item of the total number of orders made"
        data_tests:
          - not_null
      - name: product_id
        description: "The reference key pointing to the products table"
        data_tests:
          - not_null
      - name: seller_id
        description: "The reference key pointing to the sellers table"
        data_tests:
          - not_null
      - name: expected_shipping_date
        description: "The date where the product is expected to be shipped to the courier"
        data_tests:
          - not_null
      - name: price
        description: "The price of the product"
        data_tests:
          - not_null
      - name: shipping_cost
        description: "The additional cost of the product for the shipping"
        data_tests:
          - not_null
  - name: stg_order_payments
    columns:
      - name: 