
version: 2

models:
  - name: stg_customers
    description: "Staging table for the customers dataset with cleaned and standardized fields"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "A natural identifier for a customer; can be used to track repeat customers across multiple orders"
        tests:
          - not_null
      - name: zip_code_prefix
        description: "Zip code prefix of the customer, used to join with geolocation"
        tests:
          - not_null
  - name: stg_geolocation
    description: "Staging table for the geolocation dataset with cleaned and standardized fields"
    columns:
      - name: zip_code_prefix
        description: "The primary key for this table being referenced by the customers and sellers table"
        tests:
          - not_null
          - unique
      - name: latitude
        description: "Average latitude for the zip code"
        tests:
          - not_null
      - name: longitude
        description: "Average longitude for the zip code"
        tests:
          - not_null
  - name: stg_order_items
    description: "Staging table for the order items dataset with cleaned and standardized fields"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['order_id', 'order_item_num']
    columns:
      - name: order_id
        description: "The id given to each order made"
        tests:
          - not_null
      - name: order_item_num
        description: "The item sequence number within the order"
        tests:
          - not_null
      - name: product_id
        description: "The reference key pointing to the products table"
        tests:
          - not_null
      - name: seller_id
        description: "The reference key pointing to the sellers table"
        tests:
          - not_null
      - name: price
        description: "The price of the product"
        tests:
          - not_null
      - name: shipping_cost
        description: "Freight/shipping fee for the item"
        tests:
          - not_null
  - name: stg_order_payments
    description: "Staging table for the order payments dataset with cleaned and standardized fields"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - not_null
          - unique
      - name: attempts_made
        description: "Number of payment attempts made for the order"
        tests:
          - not_null
      - name: payment_installments
        description: "The total number of installments in which the product can be paid"
        tests:
          - not_null
      - name: total_payment
        description: "Total value paid for the order (including shipping)"
        tests:
          - not_null
  - name: stg_order_reviews
    description: "Staging table for the order reviews dataset with cleaned and standardized fields"
    columns:
      - name: review_id
        description: "The identifier for the review"
        tests:
          - not_null
      - name: order_id
        description: "The reference which order the review pertains to"
        tests:
          - not_null
      - name: score
        description: "Rating score (1 = worst, 5 = best)"
        tests:
          - not_null
  - name: stg_orders
    description: "Staging table for the orders dataset with cleaned and standardized fields"
    columns:
      - name: order_id
        description: "The id given to each order made"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "The reference key pertaining to the customer"
        tests:
          - not_null
      - name: status
        description: "Current lifecycle status of the order (e.g., delivered, shipped, cancelled)"
        tests:
          - not_null
  - name: stg_product_category
    description: "Staging table for the product category dataset with cleaned and standardized fields"
    columns:
      - name: category_name
        description: "Product category name in Portuguese"
        tests:
          - not_null
          - unique
  - name: stg_products
    description: "Staging table for the products dataset with cleaned and standardized fields"
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - not_null
          - unique
      - name: category_name
        description: "The category it belongs to referencing the product category table"
        tests:
          - not_null
  - name: stg_sellers
    description: "Staging table for the sellers dataset with cleaned and standardized fields"
    columns:
      - name: seller_id
        description: "The primary key for this table"
        tests:
          - not_null
          - unique
      - name: zip_code_prefix
        description: "Seller's zip code prefix, joins with geolocation"
        tests:
          - not_null