version: 2

sources:
  - name: raw
    database: ecommerce_db
    description: "Raw sources tables loaded from Kaggle datasets"
    tables:
      - name: customers
        description: "Raw dataset containing customer-level attributes, including unique IDs and location information."
        columns:
          - name: customer_id
            tests:
              - unique
              - not_null
          - name: customer_unique_id
            tests:
              - not_null
      - name: geolocation
        description: "Raw dataset mapping Brazilian zip code prefixes to geographic coordinates (latitude, longitude), used for both customers and sellers."
        columns:
          - name: geolocation_zip_code_prefix
            tests:
              - not_null
          - name: geolocation_lat
            tests:
              - not_null
          - name: geolocation_lng
            tests:
              - not_null
      - name: order_items
        description: "Raw dataset capturing the relationship between customer orders and products, including pricing and seller information."
        columns:
          - name: order_id
            tests:
              - not_null
          - name: order_item_id
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null
          - name: seller_id
            tests:
              - not_null
          - name: price
            tests:
              - not_null
      - name: order_payments
        description: "Raw dataset detailing payment information for customer orders, including payment type, installments, and amounts."
        columns:
          - name: order_id
            tests:
              - not_null
          - name: payment_type
            tests:
              - not_null
          - name: payment_installments
            tests:
              - not_null
          - name: payment_value
            tests:
              - not_null
      - name: order_reviews
        description: "Raw dataset containing customer reviews of products/orders, including review scores and comments."
        columns:
          - name: review_id
            tests:
              - not_null
          - name: order_id
            tests:
              - not_null
          - name: review_score
            tests:
              - not_null
      - name: orders
        description: "Raw dataset describing order lifecycle information, including status, purchase, approval, shipping, and delivery dates."
        columns:
          - name: order_id
            tests:
              - not_null
              - unique
          - name: customer_id
            tests:
              - not_null
          - name: order_status
            tests:
              - not_null
              - accepted_values:
                  arguments:
                    values: ['shipped', 'unavailable', 'invoiced', 'created', 'approved', 'processing', 'delivered', 'cancelled']
      - name: product_category
        description: "Raw dataset mapping Portuguese product category names to their English translations."
        columns:
          - name: product_category_name
            tests:
              - not_null
      - name: products
        description: "Raw dataset containing product-level attributes such as dimensions, weight, and category mapping."
        columns:
          - name: product_id
            tests:
              - not_null
              - unique
          - name: product_category_name
            tests:
              - not_null
      - name: sellers
        description: "Raw dataset containing seller-level attributes, including location details."
        columns:
          - name: seller_id
            tests:
              - not_null
              - unique
          - name: seller_zip_code_prefix
            tests:
              - not_null