version: 2

sources:
  - name: raw
    database: ecommerce_db
    description: "Raw sources tables loaded from Kaggle datasets"
    tables:
      - name: customers
        description: "Raw dataset which attributes pertains to customers"
        columns:
          - name: customer_id
            tests:
              - not_null
          - name: customer_unique_id
            tests:
              - not_null
          - name: zip_code_prefix
            tests:
              - not_null
          - name: city
            tests:
              - not_null
      - name: geolocation
        description: "Raw dataset which attributes pertains to the geolocation for both customers and sellers"
        columns:
          - name: zip_code_prefix
            tests:
              - not_null
          - name: latitude
            tests:
              - not_null
          - name: longitude
            tests:
              - not_null
      - name: order_items
        desciption: "Raw dataset which attributes pertains to the order-product relationship"
        columns:
          - name: order_id
            tests:
              - not_null
          - name: order_item_num
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null
          - name: seller_id
            tests:
              - not_null
          - name: 
      - name: order_payments
        description: "Raw dataset which attributes pertains to the description of payments made"
      - name: order_reviews
        description: "Raw dataset which attributes pertains to the reviews made by customers to products"
      - name: orders
        description: "Raw dataset which attributes pertains to the description of the orders made"
      - name: product_category
        description: "Raw dataset which attributes pertains to product category name and its translation"
      - name: products
        description: "Raw dataset which attributes pertains to the products"
      - name: sellers
        description: "Raw dataset which attributes pertains to the sellers"