version: 2

sources:
  - name: raw
    database: ecommerce_db
    description: "Raw sources tables loaded from Kaggle datasets"
    tables:
      - name: customers
        description: "Raw dataset which attributes pertains to customers"
        columns:
          - name: customer_id
            tests:
              - unique
              - not_null
          - name: customer_unique_id
            tests:
              - not_null
      - name: geolocation
        description: "Raw dataset which attributes pertains to the geolocation for both customers and sellers"
        columns:
          - name: geolocation_zip_code_prefix
            tests:
              - not_null
          - name: geolocation_lat
            tests:
              - not_null
          - name: geolocation_lng
            tests:
              - not_null
      - name: order_items
        description: "Raw dataset which attributes pertains to the order-product relationship"
        columns:
          - name: order_id
            tests:
              - not_null
          - name: order_item_num
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null
          - name: seller_id
            tests:
              - not_null
          - name: price
            tests:
              - not_null
      - name: order_payments
        description: "Raw dataset which attributes pertains to the description of payments made"
        columns:
          - name: order_id
            tests:
              - not_null
          - name: payment_type
            tests:
              - not_null
          - name: payment_installments
            tests:
              - not_null
          - name: payment_value
            tests:
              - not_null
      - name: order_reviews
        description: "Raw dataset which attributes pertains to the reviews made by customers to products"
        columns:
          - name: review_id
            tests:
              - not_null
          - name: order_id
            tests:
              - not_null
          - name: review_score
            tests:
              - not_null
      - name: orders
        description: "Raw dataset which attributes pertains to the description of the orders made"
        columns:
          - name: order_id
            tests:
              - not_null
              - unique
          - name: customer_id
            tests:
              - not_null
          - name: order_status
            tests:
              - not_null
      - name: product_category
        description: "Raw dataset which attributes pertains to product category name and its translation"
        columns:
          - name: product_category_name
            tests:
              - not_null
      - name: products
        description: "Raw dataset which attributes pertains to the products"
        columns:
          - name: product_id
            tests:
              - not_null
              - unique
          - name: product_category_name
            tests:
              - not_null
      - name: sellers
        description: "Raw dataset which attributes pertains to the sellers"
        columns:
          - name: seller_id
            tests:
              - not_null
              - unique
          - name: seller_zip_code_prefix
            tests:
              - not_null